swagger: '2.0'
info:
  title: wiki模版
  description: 'wiki模版相关内容,目前只包括模板相关接口'
  version: v1
host: api.ones.ai
basePath: /v1/wiki
schemes:
  - https
paths:
  '/team/{teamUUID}/space/{spaceUUID}/drafts/add':
    post:
      tags:
        - draft
      summary: 1. 创建临时草稿。
      description: "\n该接口支持以下功能：\n1. 创建临时草稿。"
      operationId: AddDraft
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/spaceUUID'
        - $ref: '#/parameters/teamUUID'
        - $ref: '#/parameters/Ones-User-ID'
        - $ref: '#/parameters/Ones-Auth-Token'
        - name: body
          in: body
          description: 请求内容为draft的信息
          required: true
          schema:
            $ref: '#/definitions/AddDraftRequest'
      responses:
        '200':
          description: 返回draft的摘要信息
          schema:
            $ref: '#/definitions/AddDraftResponse'
        '630':
          description: 没有page记录
        '801':
          description: 参数格式有误
        '817':
          description: 用户已经存在页面草稿
        '901':
          description: 内容过长
parameters:
  spaceUUID:
    name: spaceUUID
    in: path
    required: true
    type: string
  teamUUID:
    name: teamUUID
    in: path
    required: true
    type: string
  Ones-User-ID:
    name: Ones-User-ID
    in: header
    required: true
    type: string
  Ones-Auth-Token:
    name: Ones-Auth-Token
    in: header
    required: true
    type: string
definitions:
  AddDraftRequest:
    properties:
      content:
        description: 内容
        type: string
      copy_src_type:
        description: '拷贝来源类型,选填'
        type: string
        enum:
          - template
          - page
      copy_src_uuid:
        description: 被拷贝对象的UUID，选填
        type: string
      page_uuid:
        description: 页面UUID
        type: string
      status:
        description: '1: space 临时草稿, 2: page 页面草稿'
        type: integer
        format: int32
      title:
        description: 标题
        type: string
  AddDraftResponse:
    properties:
      create_time:
        description: 创建时间
        type: integer
        format: int64
      owner_uuid:
        description: owner uuid
        type: string
      page_uuid:
        description: page uuid
        type: string
      space_uuid:
        description: space uuid
        type: string
      status:
        description: '1: space 临时草稿, 2: page 页面草稿'
        type: integer
        format: int32
      uuid:
        description: 草稿的uuid
        type: string