openapi: 3.0.0
info:
  title: wiki模版
  description: 'wiki模版相关内容,目前只包括模板相关接口'
  version: v5
paths:
  '/team/{teamUUID}/space/{spaceUUID}/template/{templateUUID}':
    get:
      operationId: GetTemplateInfo
      tags:
        - template
      summary: 获取模板的信息
      parameters:
        - $ref: '../../common/parameters.yaml#/parameters/teamUUID'
        - $ref: '#/components/parameters/templateUUID'
        - $ref: '../../common/parameters.yaml#/parameters/Ones-User-Id'
        - $ref: '../../common/parameters.yaml#/parameters/Ones-Auth-Token'
        - $ref: '../../common/parameters.yaml#/parameters/spaceUUID'
      responses:
        '200':
          description: 返回template的信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/team/{teamUUID}/space/{spaceUUID}/template/{templateUUID}/attachments':
    get:
      operationId: GetAttachments
      tags:
        - template-attachment
      summary: 列出模板的附件
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/start'
        - $ref: '../../common/parameters.yaml#/parameters/spaceUUID'
        - $ref: '../../common/parameters.yaml#/parameters/teamUUID'
        - $ref: '#/components/parameters/templateUUID'
        - $ref: '../../common/parameters.yaml#/parameters/Ones-User-Id'
        - $ref: '../../common/parameters.yaml#/parameters/Ones-Auth-Token'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemplateAttachments'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/team/{teamUUID}/space/{spaceUUID}/template/{templateUUID}/attachments/update':
    post:
      operationId: UpdateTemplateAttachment
      tags:
        - template-attachment
      summary: 更新模板附件
      parameters:
        - $ref: '../../common/parameters.yaml#/parameters/spaceUUID'
        - $ref: '../../common/parameters.yaml#/parameters/teamUUID'
        - $ref: '#/components/parameters/templateUUID'
        - $ref: '../../common/parameters.yaml#/parameters/Ones-User-Id'
        - $ref: '../../common/parameters.yaml#/parameters/Ones-Auth-Token'
  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTemplateAttachment'
      responses:
        '200':
          description: 更新成功
        '400':
          description: InvalidParameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/team/{teamUUID}/space/{spaceUUID}/template/{templateUUID}/delete':
    post:
      operationId: DeleteTemplate
      tags:
        - template
      summary: 删除模板
      parameters:
        - $ref: '../../common/parameters.yaml#/parameters/spaceUUID'
        - $ref: '../../common/parameters.yaml#/parameters/teamUUID'
        - $ref: '#/components/parameters/templateUUID'
        - $ref: '../../common/parameters.yaml#/parameters/Ones-User-Id'
        - $ref: '../../common/parameters.yaml#/parameters/Ones-Auth-Token'
      responses:
        '200':
          description: Opration successful
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/team/{teamUUID}/space/{spaceUUID}/template/{templateUUID}/update':
    post:
      operationId: UpdateTemplate
      tags:
        - template
      summary: 更新模板
      parameters:
        - $ref: '../../common/parameters.yaml#/parameters/teamUUID'
        - $ref: '#/components/parameters/templateUUID'
        - $ref: '../../common/parameters.yaml#/parameters/Ones-User-Id'
        - $ref: '../../common/parameters.yaml#/parameters/Ones-Auth-Token'
        - $ref: '../../common/parameters.yaml#/parameters/spaceUUID'
      requestBody:
        description: 模版的标题和内容
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTemplateRequest'
      responses:
        '200':
          description: 更新成功
        '400':
          description: InvalidParameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/team/{teamUUID}/space/{spaceUUID}/templates':
    get:
      operationId: GetTemplates
      tags:
        - template
      summary: 列出模板
      parameters:
        - $ref: '../../common/parameters.yaml#/parameters/Ones-Auth-Token'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/start'
        - $ref: '../../common/parameters.yaml#/parameters/spaceUUID'
        - $ref: '../../common/parameters.yaml#/parameters/teamUUID'
        - $ref: '../../common/parameters.yaml#/parameters/Ones-User-Id'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Templates'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/team/{teamUUID}/space/{spaceUUID}/templates/add':
    post:
      operationId: AddTemplate
      tags:
        - template
      summary: '1.新建模板, 2. 添加到页面模板 '
      description: "\n该接口支持以下功能:\n1. 新建模板(F2020)。\n2. 添加页面模板(F2020)。\n\n示例：\n1. 新建模板， 请求内容为：\n{\n\t\"content\": \"string\",\n\t\"title\": \"string\"\n}\n\n2. 添加页面模板, 请求内容为:\n{\n\t\"copy_src_type\": \"page\",\n\t\"copy_src_uuid\": \"string\",\n}\n\n"
      parameters:
        - $ref: '../../common/parameters.yaml#/parameters/teamUUID'
        - $ref: '../../common/parameters.yaml#/parameters/Ones-User-Id'
        - $ref: '../../common/parameters.yaml#/parameters/Ones-Auth-Token'
        - $ref: '../../common/parameters.yaml#/parameters/spaceUUID'
      requestBody:
        description: 模版的标题和内容
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddTemplateRequest'

      responses:
        '200':
          description: 返回template的摘要信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddTemplateResponse'
        '400':
          description: InvalidParameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  parameters:
    templateUUID:
      name: templateUUID
      in: path
      required: true
      schema:
        type: string
    start:
      name: start
      in: query
      description: 起始元素(其实也就是offset)
      schema:
        type: integer
        format: int64
        minimum: 0
    limit:
      name: limit
      in: query
      description: 限制获取数
      schema:
        type: integer
        format: int64
        minimum: 1
        maximum: 1000
  schemas:
    AddTemplateRequest:
      type: object
      properties:
        content:
          description: 模版内容
          type: string
        copy_src_type:
          description: '拷贝来源类型,选填'
          type: string
          enum:
            - page
        copy_src_uuid:
          description: 被拷贝对象的UUID，选填
          type: string
        title:
          description: 模版标题
          type: string
    AddTemplateResponse:
      type: object
      properties:
        create_time:
          description: 创建时间
          type: integer
          format: int64
        owner_uuid:
          description: owner uuid
          type: string
        space_uuid:
          description: space uuid
          type: string
        uuid:
          description: 模版的uuid
          type: string
    Attachment:
      type: object
      properties:
        name:
          description: 附件name
          type: string
        uuid:
          description: 附件uuid
          type: string
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        desc:
          type: string
        errcode:
          type: string
        type:
          type: string
    Template:
      type: object
      properties:
        content:
          description: 模版内容
          type: string
        create_time:
          description: 创建时间
          type: integer
          format: int64
        owner_uuid:
          description: owner uuid
          type: string
        space_uuid:
          description: space uuid
          type: string
        title:
          description: 模版标题
          type: string
        update_time:
          description: 更新时间
          type: integer
          format: int64
        uuid:
          description: 模版的uuid
          type: string
    TemplateAttachments:
      type: object
      properties:
        attachments:
          description: 附件信息列表
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
        count:
          description: 返回结果的数量
          type: integer
          format: int64
        start:
          description: 起始元素
          type: integer
          format: int64
        total:
          description: 总数
          type: integer
          format: int64
    TemplateSummary:
      type: object
      properties:
        create_time:
          description: 创建时间
          type: integer
          format: int64
        owner_uuid:
          description: owner uuid
          type: string
        space_uuid:
          description: space uuid
          type: string
        title:
          description: 模版标题
          type: string
        update_time:
          description: 更新时间
          type: integer
          format: int64
        uuid:
          description: 模版的uuid
          type: string
    Templates:
      type: object
      properties:
        count:
          description: 返回结果的数量
          type: integer
          format: int64
        start:
          description: 起始元素
          type: integer
          format: int64
        templates:
          description: 模版信息列表
          type: array
          items:
            $ref: '#/components/schemas/TemplateSummary'
        total:
          description: 总数
          type: integer
          format: int64
    UpdateTemplateAttachment:
      type: object
      properties:
        add:
          description: 新增附件的列表
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
        remove:
          description: 删除附件的列表
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
    UpdateTemplateRequest:
      type: object
      properties:
        content:
          description: 模版内容
          type: string
        title:
          description: 模版标题
          type: string
